lbryum_servers:
  - lbryumx3.lbry.com:50001
use_upnp: False
delete_blobs_on_remove: True
share_usage_data: false
components_to_skip:
  - hash_announcer
  - blob_server
  - dht

save_files: false
save_blobs: false
